words = [
{no:1,english:'An',vietnamese:'An.',pronoun:'ən'},
{no:2,english:'Black',vietnamese:'Đen',pronoun:'blæk'},
{no:3,english:'Borglum',vietnamese:'Borglum.',pronoun:'borglum*'},
{no:4,english:'Dakota',vietnamese:'Dakota.',pronoun:'dəˈkoʊtə'},
{no:5,english:'French',vietnamese:'người Pháp',pronoun:'frɛnʧ'},
{no:6,english:'Hills',vietnamese:'Những ngọn đồi',pronoun:'hɪlz'},
{no:7,english:'His',vietnamese:'Của anh ấy',pronoun:'hɪz'},
{no:8,english:'Idaho',vietnamese:'Idaho.',pronoun:'ˈaɪdəˌhoʊ'},
{no:9,english:'Jefferson',vietnamese:'Jefferson.',pronoun:'ˈʤɛfərsən'},
{no:10,english:'John',vietnamese:'John',pronoun:'ʤɑn'},
{no:11,english:'Lincoln',vietnamese:'Lincoln.',pronoun:'ˈlɪŋkən'},
{no:12,english:'Mount',vietnamese:'Gắn kết',pronoun:'maʊnt'},
{no:13,english:'Nature',vietnamese:'Thiên nhiên',pronoun:'ˈneɪʧər'},
{no:14,english:'Paris',vietnamese:'Paris.',pronoun:'ˈpɛrɪs'},
{no:15,english:'Rodin',vietnamese:'Rodin.',pronoun:'ˌroʊˈdæn'},
{no:16,english:'Roosevelt',vietnamese:'Roosevelt.',pronoun:'ˈruzəˌvɛlt'},
{no:17,english:'Rushmore',vietnamese:'Rushmore.',pronoun:'ˈrəʃmɔr'},
{no:18,english:'States',vietnamese:'Những trạng thái',pronoun:'steɪts'},
{no:19,english:'Though',vietnamese:'Tuy nhiên',pronoun:'ðoʊ'},
{no:20,english:'United',vietnamese:'Hoa',pronoun:'juˈnaɪtɪd'},
{no:21,english:'Was',vietnamese:'Đã',pronoun:'wɑz'},
{no:22,english:'Washington',vietnamese:'Washington.',pronoun:'ˈwɔʃɪŋtən'},
{no:23,english:'age',vietnamese:'tuổi tác',pronoun:'eɪʤ'},
{no:24,english:'almost',vietnamese:'hầu hết',pronoun:'ˈɔlˌmoʊst'},
{no:25,english:'although',vietnamese:'Mặc du',pronoun:'ˌɔlˈðoʊ'},
{no:26,english:'asserted',vietnamese:'quả quyết',pronoun:'əˈsərtəd'},
{no:27,english:'befriended',vietnamese:'kết bạn',pronoun:'bɪˈfrɛndɪd'},
{no:28,english:'break',vietnamese:'phá vỡ',pronoun:'breɪk'},
{no:29,english:'bureaucracy',vietnamese:'quan liêu',pronoun:'bjʊˈrɑkrəsi'},
{no:30,english:'caring',vietnamese:'quan tâm',pronoun:'ˈkɛrɪŋ'},
{no:31,english:'carved',vietnamese:'chạm khắc',pronoun:'kɑrvd'},
{no:32,english:'commission',vietnamese:'Uỷ ban',pronoun:'kəˈmɪʃən'},
{no:33,english:'countenances',vietnamese:'phản công',pronoun:'ˈkaʊntənənsɪz'},
{no:34,english:'crack',vietnamese:'vết nứt',pronoun:'kræk'},
{no:35,english:'creating',vietnamese:'tạo ra',pronoun:'kriˈeɪtɪŋ'},
{no:36,english:'de',vietnamese:'từ',pronoun:'də'},
{no:37,english:'dealing',vietnamese:'xử lý',pronoun:'ˈdilɪŋ'},
{no:38,english:'death',vietnamese:'tử vong',pronoun:'dɛθ'},
{no:39,english:'died',vietnamese:'chết',pronoun:'daɪd'},
{no:40,english:'dynamited',vietnamese:'năng động',pronoun:'dynamited*'},
{no:41,english:'engendered',vietnamese:'sinh ra',pronoun:'ɛnˈʤɛndərd'},
{no:42,english:'enormity',vietnamese:'sự to lớn',pronoun:'ɪˈnɔrməti'},
{no:43,english:'famous',vietnamese:'nổi danh',pronoun:'ˈfeɪməs'},
{no:44,english:'features',vietnamese:'đặc trưng',pronoun:'ˈfiʧərz'},
{no:45,english:'federal',vietnamese:'liên bang',pronoun:'ˈfɛdərəl'},
{no:46,english:'financing',vietnamese:'tài trợ',pronoun:'fɪˈnænsɪŋ'},
{no:47,english:'finished',vietnamese:'đã kết thúc',pronoun:'ˈfɪnɪʃt'},
{no:48,english:'fissure',vietnamese:'khe nứt',pronoun:'ˈfɪʃər'},
{no:49,english:'fourteen',vietnamese:'mười bốn',pronoun:'ˌfɔrˈtin'},
{no:50,english:'granite',vietnamese:'đá hoa cương',pronoun:'ˈgrænɪt'},
{no:51,english:'granted',vietnamese:'được cấp',pronoun:'ˈgrænɪd'},
{no:52,english:'involve',vietnamese:'liên quan',pronoun:'ˌɪnˈvɑlv'},
{no:53,english:'known',vietnamese:'đã biết',pronoun:'noʊn'},
{no:54,english:'la',vietnamese:'các',pronoun:'lɑ'},
{no:55,english:'large',vietnamese:'lớn',pronoun:'lɑrʤ'},
{no:56,english:'lifetime',vietnamese:'cả đời',pronoun:'ˈlaɪfˌtaɪm'},
{no:57,english:'massive',vietnamese:'to lớn',pronoun:'ˈmæsɪv'},
{no:58,english:'moved',vietnamese:'di chuyển',pronoun:'muvd'},
{no:59,english:'national',vietnamese:'Quốc gia',pronoun:'ˈnæʃənəl'},
{no:60,english:'obstacles',vietnamese:'chướng ngại vật',pronoun:'ˈɑbstəkəlz'},
{no:61,english:'predicated',vietnamese:'dự đoán',pronoun:'ˈprɛdəˌkeɪtɪd'},
{no:62,english:'presidents',vietnamese:'tổng thống',pronoun:'ˈprɛzɪˌdɛnts'},
{no:63,english:'problems',vietnamese:'các vấn đề',pronoun:'ˈprɑbləmz'},
{no:64,english:'sculptor',vietnamese:'nhà điêu khắc',pronoun:'ˈskəlptər'},
{no:65,english:'sculpture',vietnamese:'điêu khắc',pronoun:'ˈskəlpʧər'},
{no:66,english:'side',vietnamese:'bên',pronoun:'saɪd'},
{no:67,english:'sixty',vietnamese:'sáu mươi',pronoun:'ˈsɪksti'},
{no:68,english:'started',vietnamese:'đã bắt đầu',pronoun:'ˈstɑrtɪd'},
{no:69,english:'stone',vietnamese:'cục đá',pronoun:'stoʊn'},
{no:70,english:'studied',vietnamese:'đã học',pronoun:'ˈstədid'},
{no:71,english:'treasure',vietnamese:'kho báu',pronoun:'ˈtrɛʒər'},
{no:72,english:'undaunted',vietnamese:'không nản lòng',pronoun:'ənˈdɔntɪd'},
{no:73,english:'uneventful',vietnamese:'không bình thường',pronoun:'ˌəniˈvɛntfəl'},
{no:74,english:'visionary',vietnamese:'nhìn xa trông rộng',pronoun:'ˈvɪʒəˌnɛri'},
{no:75,english:'well-known',vietnamese:'nổi tiếng',pronoun:'ˈwɛlˈnoʊn'},
{no:76,english:'within',vietnamese:'trong',pronoun:'wɪˈθɪn'},
{no:77,english:'worked',vietnamese:'đã làm việc',pronoun:'wərkt'},
{no:78,english:'youth',vietnamese:'thiếu niên',pronoun:'juθ'}
];