var words =[{no:"1",english:"Be similar to",vietnamese:"tương tự như",pronounce:"/bi ˈsɪmələr tɪ/"},
{no:"2",english:"expansion",vietnamese:"sự mở rộng",pronounce:"/iks'pænʃn/"},
{no:"3",english:"engage",vietnamese:"thuê một người, tham gia vào",pronounce:"/in'geidʤ/"},
{no:"4",english:"essential",vietnamese:"cần thiết",pronounce:"/i'senʃəl/"},
{no:"5",english:"Be capable of",vietnamese:"có khả năng làm gì",pronounce:"/bi ˈkeɪpəbəl əv/"},
{no:"6",english:"considerable",vietnamese:"đáng kể",pronounce:"/kən'sidərəbl/"},
{no:"7",english:"remarkable",vietnamese:"đáng chú ý, đáng để ý, khác thường, xuất sắc; đặc biệt, ngoại lệ",pronounce:"/ri'mɑ:kəbl/"},
{no:"8",english:"reasonable",vietnamese:"có lý, hợp lý",pronounce:"/'ri:znəbl/"},
{no:"9",english:"frequently",vietnamese:"thường xuyên",pronounce:"/ˈfrikwɛntli/"},
{no:"10",english:"innovative",vietnamese:"tân tiến, hiện đại",pronounce:"/'inouveitəri/ Cách viết khác : (innovative)  /'inouveitiv/"},
{no:"11",english:"Be eligible for",vietnamese:"có đủ khả năng, tư cách, điều kiện làm gì",pronounce:"/bi ˈɛlɪʤəbəl fər/"},
{no:"12",english:"Be responsible for",vietnamese:"chịu trách nhiệm về",pronounce:"/bi riˈspɑnsəbəl fər/"},
{no:"13",english:"symptom",vietnamese:"triệu chứng",pronounce:"/'simptəm/"},
{no:"14",english:"fare",vietnamese:"tiền vé",pronounce:"/feə/"},
{no:"15",english:"vacuum cleaner",vietnamese:"máy hút bụi",pronounce:"/'vækjuəm'kli:nə/"},
{no:"16",english:"necessitate",vietnamese:"đòi hỏi phải, bắt buộc phải",pronounce:"/ni'sesiteit/"},
{no:"17",english:"efficient",vietnamese:"hiệu quả",pronounce:"/ɪˈfɪʃənt/"},
{no:"18",english:"Be famous for",vietnamese:"nổi tiếng vì cái gì",pronounce:"/bi ˈfeɪməs fər/"},
{no:"19",english:"prompt",vietnamese:"nhanh chóng",pronounce:"/prompt/"},
{no:"20",english:"packed with",vietnamese:"đông đúc",pronounce:"/pækt wɪθ/"},
{no:"21",english:"creative",vietnamese:"sáng tạo",pronounce:"/kri:'eitiv/"},
{no:"22",english:"visible",vietnamese:"có thể nhìn thấy",pronounce:"/'vizəbl/"},
{no:"23",english:"proper",vietnamese:"đúng cách, thích hợp",pronounce:"/proper/"},
{no:"24",english:"Be aware of",vietnamese:"nhận thức được",pronounce:"/bi əˈwɛr əv/"},
{no:"25",english:"Be suitable for",vietnamese:"phù hợp với",pronounce:"/bi ˈsutəbəl fər/"},
{no:"26",english:"publicize",vietnamese:"công bố, công khai",pronounce:"/'pʌblisaiz/"},
{no:"27",english:"Be beneficial to",vietnamese:"có lợi cho",pronounce:"/bi ˌbɛnəˈfɪʃəl tɪ/"},
{no:"28",english:"reputation",vietnamese:"danh tiếng",pronounce:"/,repju:'teiʃn/"},
{no:"29",english:"Be fond of",vietnamese:"thích",pronounce:"/bi fɑnd əv/"},
{no:"30",english:"Be subject to",vietnamese:"chịu ảnh hưởng, phụ thuộc vào",pronounce:"/bi ˈsəbʤɪkt tɪ/"},
{no:"31",english:"Be exempt from",vietnamese:"được miễn",pronounce:"/bi ɪgˈzɛmpt frəm/"},
{no:"32",english:"Be equivalent to",vietnamese:"tương đương với",pronounce:"/bi ɪkˈwɪvələnt tɪ/"},
{no:"33",english:"head",vietnamese:"hướng đến",pronounce:"/hɛd/"},
{no:"34",english:"procedure",vietnamese:"quy trình, thủ tục",pronounce:"/prəˈsiʤər/"}];