var words =[{no:"1",english:"generate",type:"V,",vietnamese:"tạo ra",pronounce:"/ˈʤɛnərˌeɪt/"},
{no:"2",english:"applicant",type:"N,",vietnamese:"ứng viên",pronounce:"/'æplikənt/"},
{no:"3",english:"State of the art",type:"adjective",vietnamese:"Hiện đại nhất",pronounce:"/steɪt əv ðə ɑrt/"},
{no:"4",english:"provision",type:"N,",vietnamese:"điều khoản",pronounce:"/prəˈvɪʒən/"},
{no:"5",english:"consultant",type:"N,",vietnamese:"cố vấn",pronounce:"/kənˈsəltənt/"},
{no:"6",english:"revenue",type:"N,",vietnamese:"doanh thu",pronounce:"/ˈrɛvəˌnu/"},
{no:"7",english:"funding",type:"Undefined,",vietnamese:"quỹ",pronounce:"/fʌnd/"},
{no:"8",english:"possess",type:"Undefined,",vietnamese:"sở hữu",pronounce:"/pə'zes/"},
{no:"9",english:"motivation",type:"N,",vietnamese:"động lực",pronounce:"/ˌmoʊtəˈveɪʃən/"},
{no:"10",english:"candidate",type:"Undefined,",vietnamese:"ứng viên",pronounce:"/'kændidit/"},
{no:"11",english:"frequently",type:"Adv,",vietnamese:"thường xuyên",pronounce:"/ˈfrikwɛntli/"},
{no:"12",english:"extend",type:"V",vietnamese:"kéo dài, mở rộng",pronounce:"/ɪkˈstɛnd/"},
{no:"13",english:"city council",type:"Undefined,",vietnamese:"hội đồng thành phố",pronounce:"/ˈsɪti ˈkaʊnsəl/"},
{no:"14",english:"water",type:"Verb",vietnamese:"tưới cây",pronounce:"/'wɔ:tə/"},
{no:"15",english:"inquire",type:"Verb",vietnamese:"hỏi",pronounce:"/in'kwaiə/ Cách viết khác : (enquire)  /in'kwaiə/"},
{no:"16",english:"release",type:"V,",vietnamese:"phát hành",pronounce:"/riˈlis/"},
{no:"17",english:"inform",type:"V,",vietnamese:"thông báo",pronounce:"/in'fɔ:m/"},
{no:"18",english:"outstanding account",type:"Undefined,",vietnamese:"tài khoàn chưa thanh toán",pronounce:"/ˌaʊtˈstændɪŋ əˈkaʊnt/"},
{no:"19",english:"facilitate",type:"V,",vietnamese:"tạo điều kiện",pronounce:"/fəˈsɪləˌteɪt/"},
{no:"20",english:"conference",type:"Undefined,",vietnamese:"hội nghị",pronounce:"/'kɔnfərəns/"},
{no:"21",english:"license",type:"Undefined,",vietnamese:"giấy phép",pronounce:"/'laisəns/"},
{no:"22",english:"seminar",type:"N,",vietnamese:"hội thảo",pronounce:"/'seminɑ:/"},
{no:"23",english:"designate",type:"V,",vietnamese:"chỉ định",pronounce:"/ˈdɛzɪgˌneɪt/"},
{no:"24",english:"supervisor",type:"N,",vietnamese:"giám sát viên",pronounce:"/'sju:pəvaizə/"},
{no:"25",english:"require",type:"V,",vietnamese:"yêu cầu",pronounce:"/ˌrikˈwaɪər/"},
{no:"26",english:"annual",type:"Adj",vietnamese:"thường niên, hàng năm",pronounce:"/'ænjuəl/"},
{no:"27",english:"relevant",type:"Adj",vietnamese:"liên quan, thích hợp",pronounce:"/ˈrɛləvənt/"},
{no:"28",english:"evaluation",type:"N,",vietnamese:"sự đánh giá",pronounce:"/ɪˌvæljuˈeɪʃən/"},
{no:"29",english:"recruit",type:"Undefined,",vietnamese:"tuyển dụng",pronounce:"/ri'kru:t/"},
{no:"30",english:"take place",type:"Undefined,",vietnamese:"diễn ra",pronounce:"/teɪk pleɪs/"},
{no:"31",english:"register",type:"V",vietnamese:"đăng ký, ghi tên",pronounce:"/'redʤistə/"},
{no:"32",english:"sedentary",type:"Adj,",vietnamese:"ít vận động",pronounce:"/ˈsɛdənˌtɛri/"},
{no:"33",english:"stabilize",type:"V,",vietnamese:"ổn định",pronounce:"/ˈsteɪbəˌlaɪz/"},
{no:"34",english:"safeguard",type:"Verb",vietnamese:"bảo vệ",pronounce:"/ˈseɪfˌgɑrd/"},
{no:"35",english:"campaign",type:"N,",vietnamese:"chiến dịch",pronounce:"/kæmˈpeɪn/"},
{no:"36",english:"govern",type:"Verb",vietnamese:"quản lý",pronounce:"/ˈgəvərn/"},
{no:"37",english:"negotiate",type:"V",vietnamese:"thương thuyết, đàm phán",pronounce:"/nɪˈgoʊʃiˌeɪt/"},
{no:"38",english:"critic",type:"Undefined,",vietnamese:"nhà phê bình",pronounce:"/'kritik/"},
{no:"39",english:"pregnant",type:"Adj,",vietnamese:"mang bầu",pronounce:"/ˈprɛgnənt/"},
{no:"40",english:"prefer",type:"Undefined,",vietnamese:"thích hơn",pronounce:"/pri'fə:/"},
{no:"41",english:"concur",type:"V,",vietnamese:"đồng tình",pronounce:"/kənˈkər/"},
{no:"42",english:"contain /kənˈteɪn/",type:"V,",vietnamese:"chứa đựng",pronounce:"/kənˈteɪn /kənˈteɪn*//"},
{no:"43",english:"job description",type:"Undefined,",vietnamese:"bản mô tả công việc",pronounce:"/ʤɑb dɪˈskrɪpʃən/"},
{no:"44",english:"minimum",type:"Undefined,",vietnamese:"tối thiểu",pronounce:"/ˈmɪnəməm/"},
{no:"45",english:"undergo",type:"V,",vietnamese:"trải qua",pronounce:"/ˌəndərˈgoʊ/"},
{no:"46",english:"instructor",type:"Undefined,",vietnamese:"người hướng dẫn",pronounce:"/in'strʌktə/"},
{no:"47",english:"semester",type:"Undefined,",vietnamese:"học kỳ",pronounce:"/si'mestə/"},
{no:"48",english:"eliminate",type:"V,",vietnamese:"loại bỏ",pronounce:"/ɪˈlɪməˌneɪt/"},
{no:"49",english:"regulation",type:"N,",vietnamese:"quy định",pronounce:"/,regju'leiʃn/"},
{no:"50",english:"publish",type:"Undefined,",vietnamese:"xuất bản",pronounce:"/ˈpəblɪʃ/"},
{no:"51",english:"impact",type:"N,",vietnamese:"ảnh hưởng",pronounce:"/ˌɪmˈpækt/"},
{no:"52",english:"announce",type:"V,",vietnamese:"thông báo",pronounce:"/ə'nauns/"},
{no:"53",english:"private",type:"Adj,",vietnamese:"riêng tư",pronounce:"/ˈpraɪvət/"},
{no:"54",english:"welfare",type:"N,",vietnamese:"phúc lợi",pronounce:"/ˈwɛlˌfɛr/"},
{no:"55",english:"directly",type:"Adv,",vietnamese:"một cách trực tiếp",pronounce:"/di'rektli/"},
{no:"56",english:"surpass",type:"V,",vietnamese:"vượt qua",pronounce:"/sərˈpæs/"},
{no:"57",english:"a variety of",type:"Undefined",vietnamese:"có nhiều, đa dạng",pronounce:"/ə vərˈaɪəti əv/"},
{no:"58",english:"transfer",type:"Undefined,",vietnamese:"chuyển công tác",pronounce:"/'trænsfə:/"},
{no:"59",english:"experienced",type:"Undefined,",vietnamese:"có kinh nghiệm",pronounce:"/iks'piəriənst/"},
{no:"60",english:"assistant",type:"V",vietnamese:"phụ tá, trợ giúp",pronounce:"/ə'sistənt/"},
{no:"61",english:"coordinator",type:"Undefined,",vietnamese:"điều phối viên",pronounce:"/koʊˈɔrdəˌneɪtər/"},
{no:"62",english:"priority",type:"N,",vietnamese:"sự ưu tiên",pronounce:"/praɪˈɔrəti/"},
{no:"63",english:"pertinent",type:"Adj,",vietnamese:"thích đáng",pronounce:"/ˈpərtɪnɪnt/"},
{no:"64",english:"promising",type:"Undefined,",vietnamese:"đầy hứa hẹn",pronounce:"/promising/"},
{no:"65",english:"state-of-the-art",type:"Undefined,",vietnamese:"hiện đại nhất",pronounce:"/ˌsteɪtəvðɪˈɑrt/"}];