var words =[{no:"1",english:"attract",vietnamese:"Thu Hút",pronounce:"/ə'trækt/"},
{no:"2",english:"lively",vietnamese:"Sôi Nổi",pronounce:"/'laivli/"},
{no:"3",english:"hurt",vietnamese:"Đau Lòng",pronounce:"/hərt/"},
{no:"4",english:"keen",vietnamese:"Say Mê",pronounce:"/kin/"},
{no:"5",english:"happily",vietnamese:"Hạnh Phúc",pronounce:"/ˈhæpəli/"},
{no:"6",english:"amazingly",vietnamese:"Thật Đáng Kinh Ngạc",pronounce:"/əˈmeɪzɪŋli/"},
{no:"7",english:"annoy",vietnamese:"Làm Phiền",pronounce:"/əˈnɔɪ/"},
{no:"8",english:"cold",vietnamese:"Lạnh Lùng",pronounce:"/koʊld/"},
{no:"9",english:"knowledge",vietnamese:"Sự Hiểu Biết",pronounce:"/ˈnɑlɪʤ/"},
{no:"10",english:"nasty",vietnamese:"Thô Lỗ",pronounce:"/ˈnæsti/"},
{no:"11",english:"silly",vietnamese:"Ngớ Ngẩn",pronounce:"/ˈsɪli/"},
{no:"12",english:"boring",vietnamese:"Nhàm Chán",pronounce:"/ˈbɔrɪŋ/"},
{no:"13",english:"nice",vietnamese:"Tốt",pronounce:"/nais/"},
{no:"14",english:"realize",vietnamese:"Nhận Ra",pronounce:"/ˈriəˌlaɪz/"},
{no:"15",english:"please",vietnamese:"Làm Vui Lòng",pronounce:"/pliz/"},
{no:"16",english:"favourite",vietnamese:"Sự Yêu Thích",pronounce:"/'feivərit/"},
{no:"17",english:"behave",vietnamese:"Hành Xử",pronounce:"/bɪˈheɪv/"},
{no:"18",english:"disappointing",vietnamese:"Làm Thất Vọng",pronounce:"/ˌdɪsəˈpɔɪnɪŋ/"},
{no:"19",english:"shocking",vietnamese:"Gây Sốc",pronounce:"/ˈʃɑkɪŋ/"},
{no:"20",english:"disappointment",vietnamese:"Sự Thất Vọng",pronounce:"/ˌdɪsəˈpɔɪntmənt/"},
{no:"21",english:"thought",vietnamese:"Sự Suy Nghĩ",pronounce:"/θɔt/"},
{no:"22",english:"interest",vietnamese:"Sự Thích Thú",pronounce:"/'intrist/"},
{no:"23",english:"embarrassing",vietnamese:"Lúng Túng",pronounce:"/ɪmˈbɛrəsɪŋ/"},
{no:"24",english:"feelings",vietnamese:"Lòng Tự Ái",pronounce:"/ˈfilɪŋz/"},
{no:"25",english:"hopeful",vietnamese:"Có Hy Vọng, Đầy Hy Vọng",pronounce:"/'houpful/"},
{no:"26",english:"hate",vietnamese:"Ghét Bỏ",pronounce:"/heɪt/"},
{no:"27",english:"prefer",vietnamese:"Thích Hơn",pronounce:"/pri'fə:/"},
{no:"28",english:"gentle",vietnamese:"Dịu Dàng",pronounce:"/ˈʤɛnəl/"},
{no:"29",english:"disappointed",vietnamese:"Thất Vọng",pronounce:"/ˌdɪsəˈpɔɪnɪd/"},
{no:"30",english:"cheerful",vietnamese:"Vui Vẻ",pronounce:"/'tʃjəful/"},
{no:"31",english:"surprisingly",vietnamese:"Thật Ngạc Nhiên",pronounce:"/səˈpraɪzɪŋli/"},
{no:"32",english:"background",vietnamese:"Gia Cảnh",pronounce:"/ˈbækˌgraʊnd/"},
{no:"33",english:"dream",vietnamese:"Ước Mơ, Giấc Mơ",pronounce:"/drim/"},
{no:"34",english:"care",vietnamese:"Quan Tâm",pronounce:"/kɛr/"},
{no:"35",english:"amazing",vietnamese:"Đáng Kinh Ngạc",pronounce:"/əˈmeɪzɪŋ/"},
{no:"36",english:"think",vietnamese:"Suy Nghĩ",pronounce:"/θiɳk/"},
{no:"37",english:"creative",vietnamese:"Sáng Tạo",pronounce:"/kri:'eitiv/"},
{no:"38",english:"happiness",vietnamese:"Hạnh Phúc",pronounce:"/ˈhæpinəs/"},
{no:"39",english:"excited",vietnamese:"Nóng Lòng",pronounce:"/ɪkˈsaɪtɪd/"},
{no:"40",english:"peaceful",vietnamese:"Bình Tĩnh",pronounce:"/'pi:sful/"},
{no:"41",english:"respect",vietnamese:"Tôn Trọng",pronounce:"/rɪˈspɛkt/"},
{no:"42",english:"strict",vietnamese:"Nghiêm Khắc",pronounce:"/strɪkt/"},
{no:"43",english:"comfortable",vietnamese:"Thoải Mái",pronounce:"/'kʌmfətəbl/"},
{no:"44",english:"fool",vietnamese:"Người Ngu Xuẩn",pronounce:"/ful/"},
{no:"45",english:"bit",vietnamese:"Một Miếng, Một Chút",pronounce:"/bɪt/"},
{no:"46",english:"anxious",vietnamese:"Lo Lắng",pronounce:"/ˈæŋʃəs/"},
{no:"47",english:"patient",vietnamese:"Kiên Nhẫn",pronounce:"/'peiʃənt/"},
{no:"48",english:"poor",vietnamese:"Đáng Thương, Tội Nghiệp",pronounce:"/puə/"},
{no:"49",english:"uninteresting",vietnamese:"Không Thú Vị",pronounce:"/əˈnɪntrəstɪŋ/"},
{no:"50",english:"sensible",vietnamese:"Biết Điều",pronounce:"/ˈsɛnsəbəl/"},
{no:"51",english:"attitude",vietnamese:"Thái Độ",pronounce:"/ˈætəˌtud/"},
{no:"52",english:"pleased",vietnamese:"Hài Lòng",pronounce:"/plizd/"},
{no:"53",english:"dislike",vietnamese:"Không Thích",pronounce:"/dɪsˈlaɪk/"},
{no:"54",english:"careful",vietnamese:"Cẩn Thận",pronounce:"/ˈkɛrfəl/"},
{no:"55",english:"satisfied",vietnamese:"Hài Lòng",pronounce:"/ˈsætɪsˌfaɪd/"},
{no:"56",english:"unbelievable",vietnamese:"Khó Tin, Lạ Lùng",pronounce:"/ˌənbəˈlivəbəl/"},
{no:"57",english:"doubt",vietnamese:"Sự Nghi Ngờ",pronounce:"/daʊt/"},
{no:"58",english:"lazy",vietnamese:"Lười Biếng",pronounce:"/ˈleɪzi/"},
{no:"59",english:"frightened",vietnamese:"Sợ Hãi",pronounce:"/ˈfraɪtənd/"},
{no:"60",english:"kind",vietnamese:"Tử Tế, Ân Cần, Có Lòng Tốt",pronounce:"/kaind/"},
{no:"61",english:"selfish",vietnamese:"Ích Kỷ",pronounce:"/'selfiʃ/"},
{no:"62",english:"dangerous",vietnamese:"Nguy Hiểm",pronounce:"/ˈdeɪnʤərəs/"},
{no:"63",english:"believe",vietnamese:"Tin",pronounce:"/bɪˈliv/"},
{no:"64",english:"cruel",vietnamese:"Độc Ác, Hung Ác",pronounce:"/kruəl/"},
{no:"65",english:"angry",vietnamese:"Tức Giận",pronounce:"/ˈæŋgri/"},
{no:"66",english:"want",vietnamese:"Muốn",pronounce:"/wɔnt/"},
{no:"67",english:"bravely",vietnamese:"Dũng Cảm",pronounce:"/ˈbreɪvli/"},
{no:"68",english:"kindly",vietnamese:"Vui Lòng",pronounce:"/ˈkaɪndli/"},
{no:"69",english:"talented",vietnamese:"Có Tài",pronounce:"/ˈtæləntɪd/"},
{no:"70",english:"confusing",vietnamese:"Gây Nhầm Lẫn",pronounce:"/kənfˈjuzɪŋ/"},
{no:"71",english:"beginner",vietnamese:"Người Bắt Đầu",pronounce:"/bɪˈgɪnər/"},
{no:"72",english:"guilty",vietnamese:"Tội Lỗi",pronounce:"/ˈgɪlti/"},
{no:"73",english:"charming",vietnamese:"Duyên Dáng",pronounce:"/ˈʧɑrmɪŋ/"},
{no:"74",english:"embarrassed",vietnamese:"Xấu Hổ",pronounce:"/ɪmˈbɛrəst/"},
{no:"75",english:"negative",vietnamese:"Tiêu Cực",pronounce:"/ˈnɛgətɪv/"},
{no:"76",english:"shocked",vietnamese:"Cảm Thấy Sốc",pronounce:"/ʃɑkt/"},
{no:"77",english:"glad",vietnamese:"Vui Vẻ",pronounce:"/glæd/"},
{no:"78",english:"feel",vietnamese:"Cảm Thấy",pronounce:"/fi:l/"},
{no:"79",english:"peace",vietnamese:"Sự Yên Lặng, Sự Yên Tĩnh",pronounce:"/pis/"},
{no:"80",english:"upset",vietnamese:"Buồn Bã",pronounce:"/ˈəpˌsɛt/"},
{no:"81",english:"relax",vietnamese:"Thư Giãn",pronounce:"/ri'læks/"},
{no:"82",english:"terrified",vietnamese:"Kinh Hoàng",pronounce:"/ˈtɛrəˌfaɪd/"},
{no:"83",english:"annoying",vietnamese:"Làm Khó Chịu",pronounce:"/əˈnɔɪɪŋ/"},
{no:"84",english:"unexpected",vietnamese:"Bất Ngờ",pronounce:"/ˌənɪkˈspɛktɪd/"},
{no:"85",english:"nervous",vietnamese:"Lo Lắng",pronounce:"/'nə:vəs/"},
{no:"86",english:"relaxing",vietnamese:"Thư Giãn",pronounce:"/rɪˈlæksɪŋ/"},
{no:"87",english:"ashamed",vietnamese:"Xấu Hổ",pronounce:"/əˈʃeɪmd/"},
{no:"88",english:"idea",vietnamese:"Quan Điểm, Tư Tưởng",pronounce:"/ai'diə/"},
{no:"89",english:"worry",vietnamese:"Mối Lo Lắng",pronounce:"/ˈwəri/"},
{no:"90",english:"cry",vietnamese:"Khóc",pronounce:"/kraɪ/"},
{no:"91",english:"professional",vietnamese:"Chuyên Nghiệp",pronounce:"/prəˈfɛʃənəl/"},
{no:"92",english:"angrily",vietnamese:"Một Cách Giận Dữ",pronounce:"/ˈæŋgrəli/"},
{no:"93",english:"uninterested",vietnamese:"Thờ Ơ, Không Quan Tâm",pronounce:"/əˈnɪntrəstəd/"},
{no:"94",english:"tired",vietnamese:"Mệt Mỏi",pronounce:"/taɪərd/"},
{no:"95",english:"curiously",vietnamese:"Tò Mò",pronounce:"/ˈkjʊriəsli/"},
{no:"96",english:"bother",vietnamese:"Làm Phiền",pronounce:"/ˈbɑðər/"},
{no:"97",english:"reliable",vietnamese:"Đáng Tin Cậy",pronounce:"/rɪˈlaɪəbəl/"},
{no:"98",english:"enjoy",vietnamese:"Thích Thú",pronounce:"/in'dʤɔi/"},
{no:"99",english:"in",vietnamese:"Trong",pronounce:"/in/"},
{no:"100",english:"head",vietnamese:"Vị Trí Đứng Đầu, Người Đứng Đầu, Người Chỉ Huy, Thủ Trưởng",pronounce:"/hɛd/"},
{no:"101",english:"excitement",vietnamese:"Sự Phấn Khích",pronounce:"/ɪkˈsaɪtmənt/"},
{no:"102",english:"well-known",vietnamese:"Nổi Tiếng",pronounce:"/ˈwɛlˈnoʊn/"},
{no:"103",english:"amazed",vietnamese:"Kinh Ngạc",pronounce:"/əˈmeɪzd/"},
{no:"104",english:"happy",vietnamese:"Vui Sướng, Hạnh Phúc",pronounce:"/'hæpi/"},
{no:"105",english:"experienced",vietnamese:"Có Kinh Nghiệm",pronounce:"/iks'piəriənst/"},
{no:"106",english:"shy",vietnamese:"Nhát",pronounce:"/ʃai/"},
{no:"107",english:"brave",vietnamese:"Can Đảm",pronounce:"/breɪv/"},
{no:"108",english:"positive",vietnamese:"Tích Cực, Lạc Quan",pronounce:"/ˈpɑzətɪv/"},
{no:"109",english:"sad",vietnamese:"Buồn Bã",pronounce:"/sæd/"},
{no:"110",english:"generous",vietnamese:"Hào Phóng",pronounce:"/'dʤenərəs/"},
{no:"111",english:"like",vietnamese:"Thích",pronounce:"/laik/"},
{no:"112",english:"miss",vietnamese:"Nhớ",pronounce:"/mɪs/"},
{no:"113",english:"interesting",vietnamese:"Thú Vị",pronounce:"/'intristiɳ/"},
{no:"114",english:"memory",vietnamese:"Trí Nhớ",pronounce:"/ˈmɛməri/"},
{no:"115",english:"new",vietnamese:"Mới Mẻ",pronounce:"/nu/"},
{no:"116",english:"scary",vietnamese:"Đáng Sợ",pronounce:"/ˈskɛri/"},
{no:"117",english:"control",vietnamese:"Điều Khiển",pronounce:"/kənˈtroʊl/"},
{no:"118",english:"grateful",vietnamese:"Biết Ơn",pronounce:"/ˈgreɪtfəl/"},
{no:"119",english:"bad",vietnamese:"Xấu, Bất Lương",pronounce:"/bæd/"},
{no:"120",english:"miserable",vietnamese:"Khổ Sở",pronounce:"/ˈmɪzərəbəl/"},
{no:"121",english:"love",vietnamese:"Yêu",pronounce:"/lʌv/"},
{no:"122",english:"serious",vietnamese:"Đứng Đắn, Nghiêm Trang, Nghiêm Nghị",pronounce:"/ˈsɪriəs/"},
{no:"123",english:"brilliant",vietnamese:"Tài Giỏi, Lỗi Lạc",pronounce:"/ˈbrɪljənt/"},
{no:"124",english:"annoyed",vietnamese:"Bực Mình",pronounce:"/əˈnɔɪd/"},
{no:"125",english:"skill",vietnamese:"Kỹ Năng",pronounce:"/skil/"},
{no:"126",english:"scared",vietnamese:"Sợ Hãi",pronounce:"/skɛrd/"},
{no:"127",english:"jealous",vietnamese:"Ghen Tuông",pronounce:"/ˈʤɛləs/"},
{no:"128",english:"fun",vietnamese:"Sự Vui Đùa",pronounce:"/fən/"},
{no:"129",english:"interested",vietnamese:"Quan Tâm",pronounce:"/ˈɪntəˌrɛstɪd/"},
{no:"130",english:"trust",vietnamese:"Tin",pronounce:"/trəst/"},
{no:"131",english:"shock",vietnamese:"Cú Sốc",pronounce:"/ʃɑk/"},
{no:"132",english:"heart",vietnamese:"Tim",pronounce:"/hɑrt/"},
{no:"133",english:"dangerously",vietnamese:"Nguy Hiểm",pronounce:"/ˈdeɪnʤərəsli/"},
{no:"134",english:"stress",vietnamese:"Sự Căng Thẳng",pronounce:"/strɛs/"},
{no:"135",english:"surprising",vietnamese:"Thật Ngạc Nhiên",pronounce:"/səˈpraɪzɪŋ/"},
{no:"136",english:"clever",vietnamese:"Tài Giỏi",pronounce:"/ˈklɛvər/"},
{no:"137",english:"intelligent",vietnamese:"Thông Minh",pronounce:"/ˌɪnˈtɛləʤənt/"},
{no:"138",english:"powerful",vietnamese:"Quyền Lực",pronounce:"/ˈpaʊərfəl/"},
{no:"139",english:"stressful",vietnamese:"Gây Ra Căng Thẳng",pronounce:"/ˈstrɛsfəl/"},
{no:"140",english:"famous",vietnamese:"Nổi Tiếng",pronounce:"/ˈfeɪməs/"},
{no:"141",english:"relaxed",vietnamese:"Thoải Mái",pronounce:"/rɪˈlækst/"},
{no:"142",english:"exhausted",vietnamese:"Kiệt Sức",pronounce:"/ɪgˈzɔstɪd/"},
{no:"143",english:"disappoint",vietnamese:"Thất Vọng",pronounce:"/ˌdɪsəˈpɔɪnt/"},
{no:"144",english:"mad",vietnamese:"Điền Rồ, Điên Cuồng",pronounce:"/mæd/"},
{no:"145",english:"helpful",vietnamese:"Tốt Bụng",pronounce:"/ˈhɛlpfəl/"},
{no:"146",english:"mind",vietnamese:"Chú Ý, Để Ý",pronounce:"/maɪnd/"},
{no:"147",english:"smart",vietnamese:"Thông Minh",pronounce:"/smɑrt/"},
{no:"148",english:"feeling",vietnamese:"Cảm Giác",pronounce:"/ˈfilɪŋ/"},
{no:"149",english:"tiring",vietnamese:"Mệt Mỏi",pronounce:"/'taiə/"},
{no:"150",english:"regret",vietnamese:"Hối Tiếc",pronounce:"/rɪˈgrɛt/"},
{no:"151",english:"imagination",vietnamese:"Trí Tưởng Tượng",pronounce:"/ˌɪˌmæʤəˈneɪʃən/"},
{no:"152",english:"frightening",vietnamese:"Khủng Khiếp",pronounce:"/ˈfraɪtənɪŋ/"},
{no:"153",english:"fear",vietnamese:"Nỗi Sợ",pronounce:"/fɪr/"},
{no:"154",english:"sweet",vietnamese:"Tốt Bụng",pronounce:"/swit/"},
{no:"155",english:"surprised",vietnamese:"Ngạc Nhiên",pronounce:"/səˈpraɪzd/"},
{no:"156",english:"difficult",vietnamese:"Khó Khăn",pronounce:"/ˈdɪfəkəlt/"},
{no:"157",english:"judge",vietnamese:"Xét, Xét Đoán, Phán Đoán, Đánh Giá",pronounce:"/'dʤʌdʤ/"},
{no:"158",english:"enjoyable",vietnamese:"Thú Vị",pronounce:"/ˌɛnˈʤɔɪəbəl/"},
{no:"159",english:"exciting",vietnamese:"Thú Vị",pronounce:"/ik'saitiɳ/"},
{no:"160",english:"delighted",vietnamese:"Vui Mừng",pronounce:"/dɪˈlaɪtɪd/"},
{no:"161",english:"excitedly",vietnamese:"Hào Hứng",pronounce:"/ɪkˈsaɪtədli/"},
{no:"162",english:"surprise",vietnamese:"Làm Ngạc Nhiên, Làm Kinh Ngạc",pronounce:"/səˈpraɪz/"},
{no:"163",english:"sense",vietnamese:"Ý Thức",pronounce:"/sɛns/"},
{no:"164",english:"proud",vietnamese:"Tự Hào",pronounce:"/praʊd/"},
{no:"165",english:"stressed",vietnamese:"Căng Thẳng",pronounce:"/strɛst/"},
{no:"166",english:"hopeless",vietnamese:"Vô Vọng",pronounce:"/ˈhoʊpləs/"},
{no:"167",english:"good",vietnamese:"Tốt Bụng",pronounce:"/gud/"},
{no:"168",english:"curious",vietnamese:"Tò Mò",pronounce:"/ˈkjʊriəs/"},
{no:"169",english:"pleasure",vietnamese:"Niềm Vui Thích, Điều Thú Vị",pronounce:"/ˈplɛʒər/"},
{no:"170",english:"weak",vietnamese:"Thiếu Nghị Lực, Yếu Đuối, Mềm Yếu, Nhu Nhược",pronounce:"/wik/"},
{no:"171",english:"fancy",vietnamese:"Yêu Thích",pronounce:"/ˈfænsi/"},
{no:"172",english:"worried",vietnamese:"Lo Lắng",pronounce:"/ˈwərid/"},
{no:"173",english:"calm",vietnamese:"Điềm Tĩnh",pronounce:"/kɑm/"},
{no:"174",english:"lonely",vietnamese:"Cô Đơn",pronounce:"/ˈloʊnli/"},
{no:"175",english:"stupid",vietnamese:"Ngốc Nghếch",pronounce:"/ˈstupɪd/"},
{no:"176",english:"talent",vietnamese:"Nhân Tài",pronounce:"/ˈtælənt/"},
{no:"177",english:"honest",vietnamese:"Thật Thà",pronounce:"/ˈɑnəst/"},
{no:"178",english:"unhappy",vietnamese:"Bất Hạnh, Đáng Tiếc",pronounce:"/ənˈhæpi/"},
{no:"179",english:"easygoing",vietnamese:"Dễ Dãi",pronounce:"/ˈiziˈgoʊɪŋ/"},
{no:"180",english:"confident",vietnamese:"Tự Tin",pronounce:"/'kɔnfidənt/"},
{no:"181",english:"know",vietnamese:"Biết",pronounce:"/nou/"},
{no:"182",english:"unkind",vietnamese:"Không Tử Tế",pronounce:"/ənˈkaɪnd/"},
{no:"183",english:"polite",vietnamese:"Lịch Sự",pronounce:"/pəˈlaɪt/"},
{no:"184",english:"character",vietnamese:"Tính Cách",pronounce:"/ˈkɛrɪktər/"},
{no:"185",english:"experience",vietnamese:"Trải Qua",pronounce:"/iks'piəriəns/"},
{no:"186",english:"funny",vietnamese:"Buồn Cười",pronounce:"/'fʌni/"},
{no:"187",english:"politely",vietnamese:"Lịch Sự",pronounce:"/pəˈlaɪtli/"},
{no:"188",english:"hero",vietnamese:"Anh Hùng",pronounce:"/ˈhɪroʊ/"},
{no:"189",english:"bored",vietnamese:"Chán Nản",pronounce:"/bɔrd/"},
{no:"190",english:"afraid",vietnamese:"Sợ",pronounce:"/əˈfreɪd/"},
{no:"191",english:"hope",vietnamese:"Niềm Hy Vọng",pronounce:"/houp/"},
{no:"192",english:"certain",vietnamese:"Nhất Định",pronounce:"/ˈsərtən/"},
{no:"193",english:"confused",vietnamese:"Bối Rối",pronounce:"/kənfˈjuzd/"},
{no:"194",english:"careless",vietnamese:"Cẩu Thả",pronounce:"/ˈkɛrlɛs/"},
{no:"195",english:"crazy",vietnamese:"Điên Khùng",pronounce:"/ˈkreɪzi/"},
{no:"196",english:"mood",vietnamese:"Tâm Trạng",pronounce:"/mud/"}];